import React from 'react';
import {Metadata} from 'next';
import BasicLayout from '../layouts/basic.layout';
import GoogleAnalytics from '@bradgarropy/next-google-analytics';
import Script from 'next/script';
import '../styles/globals.css';
// import 'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap';

export const metadata: Metadata = {
  title: 'Web Evolution Studio',
  description: 'Generated by Next.js',
  other: {
    '360-site-verification': '77b0e1a676566c755d708af4c92a3524',
    'bytedance-verification-code': 'PwSvcyjJ+I/ikkOs7fGi',
    'theme-color': '#00B0FF',
  },
  icons: {
    icon: '/favicon.png',
    apple: '/logo192.png',
  },
  manifest: '/manifest.json',
};

/**
 * RootLayout
 * @param {React.ReactNode} children
 * @constructor
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <BasicLayout>
          {children}
        </BasicLayout>
        {/* Google Analytics*/}
        <GoogleAnalytics measurementId={'G-R8ZM6SVZ0K'}/>
        {/* microsoft clarity */}
        <Script id={'microsoft-clarity'} dangerouslySetInnerHTML={{
          __html: `
            (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "b91ge7rn7p");
            `,
        }}/>
        <Script
          src={'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1031326139722537'}
          crossOrigin={'anonymous'} async strategy={'afterInteractive'}
        />
      </body>
    </html>
  );
}
